# Generated by Django 3.1.7 on 2021-07-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20210425_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchquerymodel',
            old_name='md_price_max',
            new_name='md_autoex_sw',
        ),
        migrations.RenameField(
            model_name='searchquerymodel',
            old_name='md_ex_desc',
            new_name='md_ex_seller',
        ),
        migrations.RenameField(
            model_name='searchquerymodel',
            old_name='md_price_min',
            new_name='md_sokketu_sw',
        ),
        migrations.RenameField(
            model_name='searchquerymodel',
            old_name='md_or_desc',
            new_name='md_srch_url',
        ),
        migrations.RemoveField(
            model_name='searchquerymodel',
            name='md_or_title',
        ),
    ]
