# Generated by Django 3.1.7 on 2021-07-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20210703_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_newurl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='searchquerymodel',
            name='md_oldurl',
            field=models.TextField(null=True),
        ),
    ]
