# Generated by Django 3.1.7 on 2021-07-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20210706_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchquerymodel',
            old_name='md_sokketu_sw',
            new_name='md_buynow_sw',
        ),
    ]
