# Generated by Django 3.2.7 on 2021-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20210709_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjaxSliderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_name', models.CharField(max_length=50, null=True)),
                ('md_num', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchQueryModel',
        ),
        migrations.DeleteModel(
            name='UserDataModel',
        ),
    ]
